name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build
      #   run: echo ${{ github.sha }} > Release.txt
      # - name: Test
      #   run: cat Release.txt
      - name: node-setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build kms
        run: yarn build:kms
      - name: make zip file
        uses: vimtor/action-zip@v1
        with:
          files: packages/kms
          dest: packages/@dsrv-kms.zip
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          files: packages/@dsrv-kms.zip
