name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build
      #   run: echo ${{ github.sha }} > Release.txt
      # - name: Test
      #   run: cat Release.txt
      - name: node-setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build kms
        run: yarn build:kms
      - name: make zip file
        uses: vimtor/action-zip@v1
        with:
          files: packages/kms/lib
          dest: packages/kms/kms.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          files: packages/kms/kms.zip
          # @TODO 토큰 설정 권한 받은 이후
          # token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
